// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yunify.Auth.Server.Context;

namespace Yunify.Auth.Server.Migrations
{
    [DbContext(typeof(ConfigurationStoreContext))]
    [Migration("20180917173324_Create-DB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Yunify.Auth.Server.Model.ApiResourceModel", b =>
                {
                    b.Property<string>("ApiResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiResourceData");

                    b.HasKey("ApiResourceName");

                    b.ToTable("ApiResources");
                });

            modelBuilder.Entity("Yunify.Auth.Server.Model.ClientModel", b =>
                {
                    b.Property<string>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientData");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Yunify.Auth.Server.Model.IdentityResourceModel", b =>
                {
                    b.Property<string>("IdentityResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdentityResourceData");

                    b.HasKey("IdentityResourceName");

                    b.ToTable("IdentityResources");
                });
#pragma warning restore 612, 618
        }
    }
}
