// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using idsrv.server.Context;

namespace idsrv.server.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20180928195014_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("idsrv.server.Model.ApiResourceModel", b =>
                {
                    b.Property<string>("ApiResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiResourceData");

                    b.HasKey("ApiResourceName");

                    b.ToTable("ApiResources");
                });

            modelBuilder.Entity("idsrv.server.Model.ClientModel", b =>
                {
                    b.Property<string>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientData");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("idsrv.server.Model.IdentityResourceModel", b =>
                {
                    b.Property<string>("IdentityResourceName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdentityResourceData");

                    b.HasKey("IdentityResourceName");

                    b.ToTable("IdentityResources");
                });

            modelBuilder.Entity("idsrv.server.Model.SerialModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.HasKey("Id");

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("idsrv.server.Model.UserModel", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Serial");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("UserName");

                    b.HasAlternateKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
